import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

// 1. Imports for your project files
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI
import 'providers/inventory_provider.dart';
import 'screens/auth_wrapper.dart';

void main() async {
  // 2. Initialize Flutter bindings
  WidgetsFlutterBinding.ensureInitialized();

  // 3. Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    // 4. MultiProvider allows you to add more providers later (e.g., ThemeProvider)
    return MultiProvider(
      providers: [ChangeNotifierProvider(create: (_) => InventoryProvider())],
      child: MaterialApp(
        title: 'Store Inventory',
        debugShowCheckedModeBanner: false,

        // 5. Global Theme Configuration
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.teal),
          useMaterial3: true,
          // Optional: Customize input decoration globally
          inputDecorationTheme: const InputDecorationTheme(
            border: OutlineInputBorder(),
            filled: true,
            fillColor: Colors.white,
          ),
        ),

        // 6. The "Traffic Cop" widget that decides if we go to Login or Home
        home: const AuthWrapper(),
      ),
    );
  }
}
