import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
<<<<<<< HEAD
import 'firebase_options.dart'; 
import 'screens/auth_wrapper.dart'; 

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
=======
import 'package:provider/provider.dart';

// 1. Imports for your project files
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI
import 'providers/inventory_provider.dart';
import 'screens/auth_wrapper.dart';

void main() async {
  // 2. Initialize Flutter bindings
  WidgetsFlutterBinding.ensureInitialized();

  // 3. Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
>>>>>>> 9f12bfb36951e12c2bf8c4b795bce7dc8a13ef0e

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
<<<<<<< HEAD
    return MaterialApp(
      title: 'Inventory Store',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.teal),
        useMaterial3: true,
        inputDecorationTheme: const InputDecorationTheme(
          border: OutlineInputBorder(),
          filled: true,
          fillColor: Colors.white,
        ),
      ),
      // This is the gatekeeper that checks if user is logged in
      home: const AuthWrapper(),
=======
    // 4. MultiProvider allows you to add more providers later (e.g., ThemeProvider)
    return MultiProvider(
      providers: [ChangeNotifierProvider(create: (_) => InventoryProvider())],
      child: MaterialApp(
        title: 'Store Inventory',
        debugShowCheckedModeBanner: false,

        // 5. Global Theme Configuration
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.teal),
          useMaterial3: true,
          // Optional: Customize input decoration globally
          inputDecorationTheme: const InputDecorationTheme(
            border: OutlineInputBorder(),
            filled: true,
            fillColor: Colors.white,
          ),
        ),

        // 6. The "Traffic Cop" widget that decides if we go to Login or Home
        home: const AuthWrapper(),
      ),
>>>>>>> 9f12bfb36951e12c2bf8c4b795bce7dc8a13ef0e
    );
  }
}